server:
  port: 8006

spring:
  application:
    name: consul-provider-payment
#comsul注册中心地址
  cloud:
    sonsul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}