server:
  port: 80


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: feign80 #服务名
    prefer-ip-address: true
spring:
  application:
    name: cloud-feign-service

#设置feign客户端超时时间(spenFeign默认支持ribbon)
ribbon:
  #指的是建立连接，所用的时间，适用于网络状况正常的情况下。两端连接所用的时间。
  ReadTimeout: 5000 #这里是5秒钟的意思。
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 5000

  #意思是级别log级别
logging:
  level:
    #feign 日志 以什么级别监控那个接口
    #以degub的形式打印他的full级别的全日志。这样最全最细。
    com.atguigu.springcloud.service.PaymentFeignService: debug
