server:
  port: 80

spring:
  application:
    name: cloud-consumer-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true  #开启hystrix这个属性

#设置feign客户端超时时间(openFeign默认支持ribbon)
ribbon:
  #指的是建立连接，所用的时间，适用于网络状况正常的情况下。两端连接所用的时间。
  ReadTimeout: 1500 #这里是5秒钟的意思。
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 1500
